### PR TITLE
@turf/voronoi: fixed typescript types

### PR DESCRIPTION
**Pull request by gavinr**
options is optional: http://turfjs.org/docs/#voronoi

### CODE REVIEW

**Comment by gavinr** [comment]
@rowanwins can you please approve this workflow to run the unit tests? Thanks!

**Comment by JamesLMilner** [comment]
@gavinr I've run them for you :)

**Comment by gavinr** [comment]
Thanks James!

**Comment by JamesLMilner** [comment]
@gavinr - the change looks all okay to me, but I think @mfedderly is probably the best placed as he did all the knew TypeScript changes and has been keeping an eye on it.

**Review by mfedderly — APPROVED** [review]
Looks great, thanks!

**Comment by gavinr** [comment]
Thank you both!

**Pull request merged**
