### PR TITLE
Add About section to README.md

### PR DESCRIPTION
**Pull request by lyzidiamond**
@tmcw @morganherlocker I think this does a good job of introducing turf -- just the same text from [/static/docs](https://turfjs.org/static/docs). Merge if you approve.

### CODE REVIEW

**Comment by tmcw** [comment]
:+1: looks good! Eventually we might want to make these the same document, but happy to punt on that because I expect the markdown parsing will be a lil different and it's good to have this inline right now.

**Comment by lyzidiamond** [comment]
I see what you did here, @morganherlocker, and I like it!

**Comment by morganherlocker** [comment]
Made some minor edits:

- removed "About" heading, since it seems redundant in this context
- moved installation above data section -- mostly just to follow standard readme ordering

**Comment by lyzidiamond** [comment]
Awesome. Merging.

**Pull request merged**
