### PR TITLE
⬆️ [@turf/intersect][@turf/difference][@turf/union] bump polygon-clipping to 0.15.3

### PR DESCRIPTION
**Pull request by twelch**
This PR bumps turf packages to the latest `polygon-clipping` 0.15.3, which upgraded to `martinez-polygon-clipping` 0.7.0 (https://github.com/mfogel/polygon-clipping/pull/114) and has valuable improvements for features with holes (https://github.com/w8r/martinez/pull/113).

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

### CODE REVIEW

**Comment by rowanwins** [comment]
@twelch Thanks for the contribution
Although unfortunately this PR wont actually fix anything to do with holes as the martinez PR you referred to is only a devDependency for the `polygon-clipping` library that is used for benchmarks and comparing outputs.

**Comment by twelch** [comment]
Fair enough, you were involved with that PR after all 😄   Martinez 0.7 still has improvements that I require for my work, and maintain a fork of turf-intersect to get.  Let me know if anything more is needed to approve.

**Comment by twelch** [comment]
I see that the yarn lockfile changes that crept into this small PR are fairly substantial and possibly due to my running a newer (currently latest) yarn version `1.22.10` that changes the structure.  Perhaps there is a larger overall upgrade to the lockfile needed before this PR gets merged.

**Comment by twelch** [comment]
I'm just now tuning in to the work that has gone into the v7 branch - https://github.com/Turfjs/turf/pull/1432

**Comment by twelch** [comment]
I removed the lockfile changes

**Review by rowanwins — APPROVED** [review]
👍

**Comment by rowanwins** [comment]
Thanks for your contribution @twelch !

**Pull request merged**
