### PR TITLE
Bump `polygonize` dependency in @turf/polygonize

### PR DESCRIPTION
**Pull request by globetro**
This allows pulling in this fix https://github.com/NickCis/polygonize/pull/1 which would allow us to use @turfjs in React Native apps.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
All external dependencies should be using an exact version, it's very difficult to figure out what's wrong with a module when a patch fix changes the outputs drastically.

Feel free to bump the version to `1.0.2` instead.

In the next TurfJS releases everything will (should) be an exact version.

**Comment by globetro** [comment]
Sorry, I realized the fix to polygonize still isn't fully fixing the issue, closing this PR until I fix that.

**Comment by DenisCarriere** [comment]
@globetro 👍 Sounds good, yea I wouldn't know what the issue is with React Native... seems like an odd one.

Does React Native work with the other TurfJS modules? is it just Polygonize that's not working?

**Comment by globetro** [comment]
Yeah, the gist of the issue is that React Native's preprocessor seems to try to honor any babel configurations in any package dependency: https://github.com/facebook/react-native/issues/8296

It seems that it's just the `polygonize` package that is including its babel configuration in its npm package, so I've opened a PR to not include it: https://github.com/NickCis/polygonize/pull/2

Once that is merged and published as v1.0.3, then we can bump that package version here and it should be fixed. I can't be certain if all other turfjs package dependencies also have this issue.

**Comment by DenisCarriere** [comment]
@globetro Sounds like a plan! 👍

**Pull request closed without merging**
