### PR TITLE
Pass `steps` into turf-jsts, in @turf/buffer, defaults to 8

### LINKED ISSUE #1112: Buffer is not passing steps options to jsts
As seen in

https://github.com/Turfjs/turf/blob/f8fe4c1c7d463a3ae49782419ba5d8d96fb74142/packages/turf-buffer/index.js#L115

The buffer is always called as

```js
var buffered = BufferOp.bufferOp(geom, distance);
```

Whereas the `steps` parameter should be passed as a third parameter:

```js
var buffered = BufferOp.bufferOp(geom, distance, steps);
```

Otherwise, the buffer will assume the `DEFAULT_QUADRANT_SEGMENTS` as steps, which are 8.

https://github.com/bjornharrtell/jsts/blob/1.4.0/src/org/locationtech/jts/operation/buffer/BufferParameters.js#L3

(I don't know where to find the source code for `jsts-es` so I'm just guessing it's pretty similar to the link above.

### PR DESCRIPTION
**Pull request by cheeaun**
This fixes #1112 where the `steps` option is not passed into `turf-jsts`.

I've also changed the default value for `steps` in `README` to **8**, since `turf-jsts` defaults to 8, here: https://github.com/DenisCarriere/turf-jsts/blob/8bd0e262e4cf229935d481eef9cff7af01aaf625/src/org/locationtech/jts/operation/buffer/BufferParameters.js#L92

### CODE REVIEW

**Comment by romaxa** [comment]
@stebogit @DenisCarriere - could you merge this PR?

**Comment by romaxa** [comment]
Ping, anyone? please merge this PR

**Comment by rowanwins** [comment]
Hi @romaxa 

We're currently working on a major overhaul of Turf in the v7 branch and we're trying to do away with the jsts dependency for the buffer module. Packaging and publishing on the v6 branch are pretty broken at the moment so it's unlikely that I can easily merge this in sorry :(

I've got a work in progress buffer module happening over at [this repo](https://github.com/rowanwins/geojson-buffer) which I'm hopeful will be a suitable replacement. It includes the setting for steps.

Cheers
Rowan

**Comment by mfedderly** [comment]
Closing in favor of https://github.com/Turfjs/turf/pull/1425. Thanks!

**Pull request closed without merging**
