### PR TITLE
Add CDNJS version badge in readme

### PR DESCRIPTION
**Pull request by kennynaoh**
This will add the badge to show its version on CDNJS and also link to its page on CDNJS!

### CODE REVIEW

**Comment by tmcw** [comment]
Thanks for the contribution! We still have some work to do on CDNJS: the turf package switched from being `turf` to being `@turf/turf` - in other words, it is now [namespaced](http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages) in order to make it easier for multiple contributors to work on the project. CDNJS, as far as I know, is still tracking the `turf` project, hence the older version presented on this badge and on the site. In order to be up to date, we'll need to get CDNJS tracking the new `@turf/turf` project.

**Comment by kennynaoh** [comment]
Would you like send a PR to CDNJS?
Thanks!

**Comment by tmcw** [comment]
Sure, if someone wants to update the CDNJS representation, go for it. For the time being, we're relying on [unpkg](https://unpkg.com/#/) for builds - that's what turf-www and the rest of the readme points to.

**Comment by tmcw** [comment]
After thinking about the situation in #404, I've decided to stop pointing to the CDNJS link. unpkg is a complete replacement that will be continuously updated, automatically. Thanks for this PR and sorry for the wasted effort: I should have communicated this more clearly when we initially started moving toward npmcdn.

**Comment by kennynaoh** [comment]
You're welcome

**Pull request closed without merging**
