### PR TITLE
feat(@turf/boolean-contains): Add MultiPolygon support

### PR DESCRIPTION
**Pull request by Debakel**
Adds support for MultiPolygons to `booleanContains()`.

Closes https://github.com/Turfjs/turf/issues/2337

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

### CODE REVIEW

**Review by rowanwins — APPROVED** [review]
This looks great thanks @Debakel - I'm just waiting for CI to pass before merging. And the team is hoping that we'll get a release out soon

**Comment by antonmelbardis** [comment]
@rowanwins hi! When is this going to be released?

**Comment by rowanwins** [comment]
Hi @antonmelbardis - this should now be available in [7.0.0-alpha.0](https://www.npmjs.com/package/@turf/turf/v/7.0.0-alpha.0) which is available on npm

**Comment by antonmelbardis** [comment]
@rowanwins thank you sir!

**Comment by nick-romano** [comment]
fyi- still getting `Error: feature2 MultiPolygon geometry not supported` on `7.0.0-alpha.0`

**Comment by antonmelbardis** [comment]
@rowanwins @nick-romano yeah, the issue is still there unfortunately

**Comment by Debakel** [comment]
> fyi- still getting `Error: feature2 MultiPolygon geometry not supported` on `7.0.0-alpha.0`

@antonmelbardis @nick-romano The PR implemented `booleanContains(feature1, feature2)` only for cases where `feature1` is a MultiPolygon and `feature2` is a Polygon. Reversed operands are still not supported (but seems like there's already another PR for this:  https://github.com/Turfjs/turf/pull/2357).

➡️ It's only possible to check wether a Polygon is contained by a MultiPolygon and not vice-versa.  
➡️ It's currently not possible to check wether a MultiPolygon contains a Point, Line or any other geometry type than Polygon.

**Comment by markstos** [comment]
I'm looking for point(MultiPolygon, Point), but maybe there's another way to accomplish that.

**Pull request merged**
