### PR TITLE
turf-points-within-polygon: Allow MultiPolygons in the types

### PR DESCRIPTION
**Pull request by woutervh-**
The implementation of turf-points-within-polygon allows MultiPolygon features to be passed, but the types only allow Polygon features. This fix will allow both types.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Added a few new JSDocs `@link`:
- `{@link Points}`
- `{@link (Multi)Point}`
- `{@link (Multi)Points}`
- `{@link LineStrings}`
- `{@link (Multi)LineString}`
- `{@link (Multi)LineStrings}`
- `{@link Polygons}`
- `{@link (Multi)Polygon}`
- `{@link (Multi)Polygons}`

**Comment by DenisCarriere** [comment]
Maybe we should also allow for `Feature<Polygon|MultiPolygon>` to be allowed as well... Having to create a FeatureCollection for the sake of creating a FeatureCollection is a bit ridiculous.

```js
var searchWithin = turf.featureCollection([
    turf.polygon([[
        [-46.653,-23.543],
        [-46.634,-23.5346],
        [-46.613,-23.543],
        [-46.614,-23.559],
        [-46.631,-23.567],
        [-46.653,-23.560],
        [-46.653,-23.543]
    ]])
]);
//=points
var ptsWithin = turf.pointsWithinPolygon(points, searchWithin);
```

**Comment by woutervh-** [comment]
Hi @DenisCarriere , not sure why this was assigned to me. It looks like everything in this PR was merged to master including your suggestion about allowing Features.

**Comment by DenisCarriere** [comment]
Don't worry about the Assigned, this is mostly to keep track on who did what when we publish the next release.

Makes it easier to see the contributors on the closed PR/Issues.

image

https://github.com/Turfjs/turf/milestone/13?closed=1

And then when we publish a minor/major release we add **contributors** to the release notes:

https://github.com/Turfjs/turf/issues/932

image

**Pull request merged**
