### PR TITLE
Point grid fix

### PR DESCRIPTION
**Pull request by stebogit**
@DenisCarriere I added the `centered` param to `@turf/point-grid` to solve #613.
Please have a look at it.

### CODE REVIEW

**Comment by stebogit** [comment]
@DenisCarriere sorry I just realized I should have branched out from master... 😭 
How can I fix this mess?? 😩

**Comment by DenisCarriere** [comment]
@stebogit lol ;) The joys of Git branches.

I've created a new branch from the master branch on Turf [`point-grid`](https://github.com/Turfjs/turf/tree/point-grid).

You can send your commits to that branch.

**Comment by stebogit** [comment]
@DenisCarriere Thanks! I guess I could have created another branch from master myself, but I was not sure it was the best solution 😅

**Comment by DenisCarriere** [comment]
Closing due to https://github.com/Turfjs/turf/pull/650

**Pull request closed without merging**
