### PR TITLE
Update isolines isobands

### PR DESCRIPTION
**Pull request by DenisCarriere**
# Refactoring `@turf/isolines` & `@turf/isobands`

CC: @stebogit Whenever you have time, do you want to update the `grid-to-matrix` & `matrix-to-grid` libraries? I can send a PR to your repos with the changes.

### CODE REVIEW

**Comment by stebogit** [comment]
Thanks @DenisCarriere I'll certainly do that as soon as I can.
BTW I saw [your PR](https://github.com/stebogit/grid-to-matrix/pull/4), thanks! 👍

**Comment by DenisCarriere** [comment]
I might need to update that PR since I've done a few changes in this, I'll update it

**Comment by stebogit** [comment]
That's great! Thanks 😜 
However, if you can't don't worry, I'll check your latest changes here

**Comment by DenisCarriere** [comment]
@stebogit I'm on a roll 🎢 🚀  It's not taking me too long to do the changes

**Comment by DenisCarriere** [comment]
Going to merge this now, but we can swap out the files once both of the modules are published.

**Pull request merged**
