### PR TITLE
Update Generate Readmes script

### PR DESCRIPTION
**Pull request by DenisCarriere**
## Update Generate Readmes script

- Windows compatible
- Can be executed from anywhere
- Added progress bar

@stebogit @rowanwins Can you try out the new `generate-readme` script or use `npm run docs` in the root directory. The big change is making this script cross-platform.

Added progress bar for progress status:

image

@tmcw ❤️ [DocumentationJS](https://github.com/documentationjs/documentation) 👍

### CODE REVIEW

**Comment by rowanwins** [comment]
Hi @DenisCarriere 

Unfortunantly Im still without laptop, hopefully I'll get something this week and will be up and running over the weekend.

Cheers

**Comment by DenisCarriere** [comment]
That's unfortunate 😢 I hope you can get yourself up and running soon!

**Comment by stebogit** [comment]
@DenisCarriere sorry I couldn't try it before.
However I can't run the script, this is what I tried (from the root directory) and not even `npm run docs` seems worked. Do you see I'm doing something wrong?

screen shot 2017-05-28 at 8 12 15 pm

**Comment by DenisCarriere** [comment]
@stebogit Did you install the dependencies first? `$npm install` or `$yarn`

**Comment by stebogit** [comment]
Yes `npm i`

**Comment by DenisCarriere** [comment]
You sure? Did you use `npm install` in the root directory?

Can't replicate the issue.

```bash
# root @ ubuntu in ~/turf on git:master o [3:40:36] 
$ node -v
v7.10.0

# root @ ubuntu in ~/turf on git:master o [3:40:37] 
$ yarn
yarn install v0.24.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 2.56s.

# root @ ubuntu in ~/turf on git:master o [3:40:41] 
$ npm run docs

> @4.0.0 docs /root/turf
> node ./scripts/generate-readmes

  progress [====================] 10/bps 100% 0.0s
```

**Comment by DenisCarriere** [comment]
@stebogit Can you clone a new repo and see if it works with a fresh Git repo?

**Comment by stebogit** [comment]
@DenisCarriere a fresh Git repo worked fine! Thanks for the tip
screen shot 2017-05-28 at 10 44 55 pm

The mispell is from [`CONTRIBUTING.md`](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md) 😅

**Comment by DenisCarriere** [comment]
OH really.. :P ops! That mispell came from me 🤦‍♂️ 
https://github.com/Turfjs/turf/commit/aa184548c8a23c96d390f27b2193ce8d060c193b

**Pull request merged**
