### PR TITLE
Support TS node16, nodenext and bundler module resolutions

### PR DESCRIPTION
**Pull request by evgenyt1**
Currently `@turf/turf` doesn't support modern node16, nodenext and bundler module resolution strategies of TypeScript. 
When "exports" is defined in `package.json`, a custom condition `types` should be added there as well.

[More on moduleResolution](https://www.typescriptlang.org/tsconfig#moduleResolution)

Also info on [TypeScript's package.json Exports, Imports, and Self-Referencing ](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing)

### CODE REVIEW

**Comment by JamesLMilner** [comment]
Resolves https://github.com/Turfjs/turf/issues/2307

**Review by JamesLMilner — APPROVED** [review]

**Review by twelch — APPROVED** [review]

**Comment by JamesLMilner** [comment]
Thanks @evgenyt1 ! 👍🏻

**Comment by markcarroll** [comment]
@JamesLMilner any idea when this will be released?

**Comment by kevinschaich** [comment]
@markcarroll  & others - `npm i @turf/turf@7.0.0-alpha.2` did the trick for me and fixes all my type issues

image

**Pull request merged**
