### PR TITLE
Add formerly failing test case for turf-intersect from issue #412

### PR DESCRIPTION
**Pull request by drewbo**
Includes a small GeoJSON test fixture for reproducing a former error noted in #412 (similar error in both `turf-intersect` and `turf-union` although this fixture was created specifically for the former) h/t @DenisCarriere 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occured.
- [x] Run `npm run lint` to ensure code style at the turf module level.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Can you also push the `test/out` at the same time.

**Comment by drewbo** [comment]
@DenisCarriere will do; looks like there are some unrelated `turf-inside` errors throwing?

**Comment by DenisCarriere** [comment]
@drewbo I noticed that too, I fixed that in the last commit.

**Comment by DenisCarriere** [comment]
Looks like it's valid.

I fixed the `test/out` feature, it has to be generated by doing `npm t`.

image

**Pull request merged**
