### PR TITLE
Initial commit of boolean-intersects

### PR DESCRIPTION
**Pull request by rowanwins**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

Submitting a new TurfJS Module.

- [x] Overview description of proposed module.
- [x] Include JSDocs with a basic example.
- [x] Execute `./scripts/generate-readmes` to create `README.md`.
- [x] Add yourself to **contributors** in `package.json` using "Full Name <@GitHub Username>".

Here we go, the long awaited booleanIntersects module - I've just gone for the path of least resistance at the moment by returning the opposite of `booleanDisjoint` so performance could probably be improved but oh well :)

### CODE REVIEW

**Comment by rowanwins** [comment]
Getting some weird yarn lock related error for this module which is killing travis - any ideas @DenisCarriere ?

**Comment by DenisCarriere** [comment]
> Getting some weird yarn lock related error for this module which is killing travis - any ideas 

I'll look into this, it is strange...

**Comment by DenisCarriere** [comment]
@rowanwins ... there's no `index.js`

I've added `index.js` in the `.gitignore` since everything "new" will be moved towards Typescript.

I'll convert the `index.js` => `index.ts` and use the new config from: https://github.com/Turfjs/turf/pull/1250

**Comment by DenisCarriere** [comment]
@rowanwins Can you push up the `index.js`

**Comment by rowanwins** [comment]
Hmmm renamed index.js to index.ts but still seems broken...

**Comment by DenisCarriere** [comment]
@rowanwins Fixed & merged!

**Pull request merged**
