### PR TITLE
New `@turf/meta` methods `lineEach` and `lineReduce`

### PR DESCRIPTION
**Pull request by stebogit**
Following https://github.com/Turfjs/turf/issues/881
@rowanwins @DenisCarriere not sure if the tests I set up are enough though.
Should these methods support also collections?

```js
/**
 * Iterate over line or ring coordinates in LineString, Polygon, MultiLineString, MultiPolygon Features or Geometries,
 * similar to Array.forEach.
 *
 * @name lineEach
 * @param {Geometry|Feature<LineString|Polygon|MultiLineString|MultiPolygon>} geojson object
 * @param {Function} callback a method that takes (currentLine, lineIndex, lineSubIndex)
 * @example
 * var mtLn = turf.multiLine([
 *   turf.lineString([[26, 37], [35, 45]]),
 *   turf.lineString([[36, 53], [38, 50], [41, 55]])
 * ]);
 *
 * turf.lineEach(mtLn, function (currentLine, lineIndex) {
 *   //=currentLine
 *   //=lineIndex
 * });
 */
function lineEach(geojson, callback) {
```

```js
/**
 * Reduce features in any GeoJSON object, similar to Array.reduce().
 *
 * @name lineReduce
 * @param {Geometry|Feature<LineString|Polygon|MultiLineString|MultiPolygon>} geojson object
 * @param {Function} callback a method that takes (previousValue, currentFeature, featureIndex)
 * @param {*} [initialValue] Value to use as the first argument to the first call of the callback.
 * @returns {*} The value that results from the reduction.
 * @example
 * var mtp = turf.multiPolygon([
 *   turf.polygon([[[12,48],[2,41],[24,38],[12,48]], [[9,44],[13,41],[13,45],[9,44]]]),
 *   turf.polygon([[[5, 5], [0, 0], [2, 2], [4, 4], [5, 5]]])
 * ]);
 *
 * turf.lineReduce(mtp, function (previousValue, currentLine, lineIndex, lineSubIndex) {
 *   //=previousValue
 *   //=currentLine
 *   //=lineIndex
 *   //=lineSubIndex
 *   return currentLine
 * }, 2);
 */
function lineReduce(geojson, callback, initialValue) {
```

## `lineEach` & `lineReduce` supports the following:
- ✅ `lineString` based Geometries
- ❌  throws error at `Point` & `MultiPoint`
- ✅ `Feature` & `Geometry`
- ❌ throws error at `FeatureCollection` & `GeometryCollection`
- ❌ throws error at `Feature<null>`

### CODE REVIEW

**Comment by stebogit** [comment]
@DenisCarriere this is new... 🤔 
Did you modified the `types` test? I don't understand though why would it fail here since this branch is straight out of master.

screen shot 2017-09-04 at 2 08 21 am

**Comment by DenisCarriere** [comment]
@stebogit Ops, yes I did change types... it was kinda experimental at first... I'll look into that.

**Comment by DenisCarriere** [comment]
> not sure if the tests I set up are enough though. Should these methods support also collections?

So far all the `@turf/meta` methods support Feature & FeatureCollection with all geometry types, might be worth doing the same for this, even if it's a Geometry Point, it would simply return no callbacks but still be a valid input.

**Comment by DenisCarriere** [comment]
## `lineEach` & `lineReduce` supports the following:
- ✅ Only `lineString` based Geometries (throws errors at `Point` & `MultiPoint`)
- ✅ Only `Feature` & `Geometry` (throws an error at `FeatureCollection` & `GeometryCollection`)

**Pull request merged**
