### PR TITLE
V5.0 Release Notes

### PR DESCRIPTION
**Pull request by DenisCarriere**
@rowanwins @stebogit You think you can give me a hand with the v5.0 release notes, we don't have to make them so explicit, but at least enough information for this major release.

There's been SOOO many PR's & Issues, so a lot of them will be duplicates.

Also we should look into the opened `v5.0` issues, most of them can be bumped to `v5.1` or closed.

https://github.com/Turfjs/turf/milestone/4

### CODE REVIEW

**Comment by stebogit** [comment]
I closed few `major-release` issues and bumped others to `v5.1`, although some of them would probably not get done soon anyway.
Now the `v5.0` issues left open should be all closed/fixed with the actual release.

**Comment by rowanwins** [comment]
Urgh I wrote up a fair whack but I've lost them somewhere in git world... Please come back!

**Comment by rowanwins** [comment]
Found em :)

**Comment by amenadiel** [comment]
Please remember to bump versions of dependencies (e.g. simplepolygon) as well, if they are still being used, to avoid falling in dupe deps hell

**Comment by DenisCarriere** [comment]
@amenadiel At the moment, `simplepolygon` is internal to TurfJS, once `simplepolygon` updates to ES modules and bumps the dependencies to v5.0 we can re-add it as a dependency.

https://github.com/Turfjs/turf/tree/master/packages/turf-unkink-polygon/lib

**Pull request merged**
