### PR TITLE
Adds doc note on `@turf/polygonize`

### PR DESCRIPTION
**Pull request by stebogit**
Ref. #819

cc: @NickCis @DenisCarriere

### CODE REVIEW

**Comment by NickCis** [comment]
I'm currently working on an implementation of [unary union](https://github.com/nickcis/unary-union). Perhaps it's better to wait until I finish it in order to update the docs with a real solution.

**Comment by stebogit** [comment]
@NickCis do you think you're going to have it done fairly soon? My goal was basically to close #819 to keep the list as short as possible.
We can easily modify again the docs whenever your module is done.

BTW were you thinking to add [`unary-union`](https://github.com/NickCis/unary-union) to `@turf/polygonize` to avoid the issue entirely?

**Comment by DenisCarriere** [comment]
@NickCis Nice! Looks like you are doing some good progress on `unary-union`, looking forward to see everything 100% tested and good to go.

Feel free to create a TurfJS wrapper for your module, `@turf/unary-union` which we could then use internally for `polygonize`.

I'm happy to see that you're `dist` is a babel ES5 output 👍

**Comment by DenisCarriere** [comment]
> @stebogit My goal was basically to close #819

It's good to update the docs, however this still wouldn't solve the issue.

I really like the idea of the `unary-union` module, I think it will be used a lot! (well I am personally going to use it! 😄)

**Comment by DenisCarriere** [comment]
> BTW were you thinking to add unary-union to @turf/polygonize to avoid the issue entirely?

I'm pretty sure that would be the intent... I would suggest we do that 👍 .

**Comment by stebogit** [comment]
> It's good to update the docs, however this still wouldn't solve the issue.

Isn't the current issue just a lack of info on a (currently) missing step to avoid the unexpected (but [not wrong](https://github.com/Turfjs/turf/issues/819#issuecomment-311839892) apparently) result? That's why the `docs` label.
Otherwise we might label it as `bug` and keep it open until `unary-union` is available.
However I would not consider this a bug.

**Comment by NickCis** [comment]
From a developer point of view, `polygonize` works as expected, the docs clearly say:

> Polygonizes a set of lines that represents edges in a planar graph. **Edges must be correctly noded, i.e., they must only meet at their endpoints**.

But, from an user's perspective `polygonize` lacks of `unary-union` functionality.

I would suggest to keep the issue open until i finish the `unary-union` implementation. I can't give a estimated time since i'm only working on it on my free time.

**Comment by DenisCarriere** [comment]
@NickCis Big thanks for those `unary-union` contributions. 👍 

@stebogit We can merge these `docs` notes and whenever we update `polygonize` with `unary-union` we can re-update the docs accordingly.

**Comment by rowanwins** [comment]
Gday @NickCis

Nice job on the unary union stuff, that would certainly be super useful for our dissolve module. 

As an FYI we've also been trying to provide a bit of support to the `martinez` (repo)[https://github.com/w8r/martinez] by @w8r which does the full range of clip, difference, union etc. Not sure if you've seen that but with checking out.

And on a side note it would be great if someone could publish a sweepline module to stop people from having to reinvent that wheel as well, I'm sure it would be a handy module for a range of things.

**Comment by w8r** [comment]
> And on a side note it would be great if someone could publish a sweepline module to stop people from having to reinvent that wheel as well, I'm sure it would be a handy module for a range of things.

@ggolikov is working on that right now, btw

**Pull request merged**
