### PR TITLE
Upgrade typescript

### PR DESCRIPTION
**Pull request by mfedderly**
Supposedly this should give us performance gains, but I'm not seeing it in the PR build timings. I'm a little hesitant to upgrade Typescript just for maintenance sake because we've seen correctness issues internally with a bunch of our Typescript upgrades recently.

We may be able to leverage some of the newer features to clean up tsconfigs perhaps?

### CODE REVIEW

**Comment by twelch** [comment]
I'm okay with upgrading just for maintenance sake, I think it reduces the amount of change at any one time, spreads it out.

**Comment by twelch** [comment]
Do you think this PR is ready and useful to merge now?  Or perhaps land after next release.

**Comment by mfedderly** [comment]
Lets land it after #2682 gets merged, that's probably the highest priority PR outstanding.

**Comment by smallsaucepan** [comment]
> Lets land it after https://github.com/Turfjs/turf/pull/2682 gets merged

For the archives, have chatted over on #2702 (successor to #2682) and will merge this upgrade first instead.

**Review by smallsaucepan — APPROVED** [review]

**Pull request merged**
