### PR TITLE
Added category for translations of turfjs in other languages

### PR DESCRIPTION
**Pull request by shashanktomar**
Turfjs is used widely for geospatial calculations. We at [hammerhead](http://www.hammerhead.io/) translated it to golang, we use this golang implementation in three different codebases: server-side, android and ios.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occured.
- [x] Run `npm run lint` to ensure code style at the turf module level.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Thanks for the efforts, however `turfgo` isn't a mirror of what is currently implemented in TurfJS.

In it's current state, I don't think we should be including this. 👎

**Comment by shashanktomar** [comment]
Hi @DenisCarriere, thanks for considering it. All our existing implementations are exact replication of Turfjs features, including the test cases and the remaining one are under Feature tag in issues. Can you please elaborate a bit more on not being the exact mirror of TurfJs, it would help us in taking it forward.

**Comment by DenisCarriere** [comment]
You're missing many of the core modules `@turf/meta`,`@turf/helpers`, `@turf/invariant` and so on. I would also recommend adding more documentation in your README.md
Keep up the hard work, however there seems to be a lot more work needed.

Another thing I noticed, you're [`Point` type](https://godoc.org/github.com/hammerheadnav/turfgo#Point) is using LatLng when the GeoJSON spec is suppose to be LngLat (xy), this would create massive confusion especially since TurfJS is entirely built on the GeoJSON spec.

Sorry, can't merge this at the moment.

**Comment by shashanktomar** [comment]
Thanks a lot for the pointers @DenisCarriere we will keep contributing to the code.

**Pull request closed without merging**
