### PR TITLE
Added new point-to-polygon-distance package

### LINKED ISSUE #1743: Distance to Polygon / MultiPolygon from Point
Opened new issue as requested by @rowanwins from #252 .

Currently there is no native way to achieve distance to Polygon (and Multi-Polygon) from a point using Turf.

There was a suggestion in the previous issue to use the vertexes and measure the distance to those, but we end up with the following issue:

closest-point-to-polygon

In this image, **B** is clearly the closest point to the polygon, but using the above algorithm we'd end up with point **A**.

I've come up with the following solution for now:

```tsx
const distanceKm = pointToLineDistance(point, polygonToLineString(polygon));

if (booleanPointInPolygon(point, polygon)) {
  return  distanceKm * -1;
} else {
  return distanceKm;
}
```

Using this over an array of Polygons allows me to achieve what I want. (I want to compare the distances of an array of Polygons to a Point and pick out the one which is the closest).

Still need to add support for `MultiPolygon`s (as `polygonToLineString` doesn't support them) - but that's as easy as splitting the geometry's coordinate array into multiple regular `Polygons` and finding the shortest distance within that group and choosing the shortest.

Since there is no direct function for Polygons, it makes use of `polygonToLineString()` to convert them to lines first and run the distance checks on that.

If the point is inside the Polygon, I return the negative value of the distance (how far inside the polygon the point is).

### PR DESCRIPTION
**Pull request by pachacamac**
Please fill in this template. Use a meaningful title for the pull request. Include the name of the package modified.

- [x] Is this a bug fix, new functionality, or a breaking change?
    - new functionality
- [x] Have read and followed the steps for [preparing a pull request](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#preparing-a-pull-request).

Submitting a new TurfJS Module.

- [x] Overview description of proposed module.
- [x] Include JSDocs with a basic example.
- [x] Execute `./scripts/generate-readmes` to create `README.md`.
- [x] Add yourself to **contributors** in `package.json` using "Full Name <@GitHub Username>".

Resolves  #1743

### CODE REVIEW

**Comment by smallsaucepan** [comment]
Looking good thanks @pachacamac. Glad to see it works with polygon holes as well.

Before it's ready to merge we might need to flesh it out in a couple of areas:

1. Allowing options in line with sister functions like pointToLineDistance. For example, being able to pass Units (meters, miles, yards).
1. Accepting the widest possible "complexity" of meaningful arguments. So, for the point a user can pass a simple number array (Position), or a bare geometry (Point), or a full on feature with properties (Feature\<Point\>). So the arguments would look like this instead:
`point: Feature<Point> | Point | Position`
`polygon: Feature<Polygon | MultiPolygon> | Polygon | MultiPolygon`
1. Only a nice to have, though including a test that addresses the example in the [original issue](https://github.com/Turfjs/turf/issues/1743#issue-480518709) would be good for closure.

Sorry if that's more involved than you expected. Happy to co-author though if your time is limited.

**Comment by pachacamac** [comment]
Thanks for pointing out the options. Missed that I can just forward this to the `pointToLineDistance` function. I also added a test that roughly reflects the initial issue question. For the sake of not complicating my test fixture setup I won't print out which point is the closest but `pointB` is the closest ;) which can be checked by comparing the expected distances of the three fixture points in the `long-lines-poly.geojson`.
I also added the expected unit to the test fixtures to validate that the unit conversion is working as expected.

**Comment by pachacamac** [comment]
@smallsaucepan anything else needed from my side?

**Review by smallsaucepan — CHANGES_REQUESTED** [review]
Thanks for this @pachacamac. Looks good.

One final task - could you please add this to the packages/turf/ package as well? That's the aggregator package that pulls in all the other turf-* packages for easy importing.

Pretty sure all you need to do is add point-to-polygon-distance as a package dependency, and re-export the main function from index.ts

**Comment by pachacamac** [comment]
@smallsaucepan done 👍

**Review by smallsaucepan — APPROVED** [review]

**Comment by smallsaucepan** [comment]
Thanks @pachacamac. Let's give it a spin through CI.

**Comment by smallsaucepan** [comment]
Little bump in the road related to the pnpm-lock file. Pushed a quick fix and CI is green, so this is ready to merge 🎉 

Thanks for your work on this @pachacamac. This was our most 👍-ed outstanding issue.

**Pull request merged**
