### PR TITLE
Allow negative numbers in rhumb destination

### PR DESCRIPTION
**Pull request by rowanwins**
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

Previously in `rhumb-destination` the distance argument had to be positive, however this meant I couldn't use it as a replacement in `turf/along`. This also gives us consistency with the standard `destination` module.

### CODE REVIEW

**Comment by rowanwins** [comment]
Not sure why travis is failing sorry...

**Comment by DenisCarriere** [comment]
@rowanwins Looks like NodeJS 10.0 came out and is causing issues with Rollup &  `@std/esm`

```
lerna ERR! (node:6131) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

I downgraded our Travis CI config file to only test using Node 9.x

**Comment by rowanwins** [comment]
Ah cool thanks @DenisCarriere . If you can merge this in and republish it to npm at some stage i'll then get on and update `@turf/along`.

Cheers

**Comment by DenisCarriere** [comment]
Published under `@turf/rhumb-destination@6.0.3`

**Pull request merged**
