### PR TITLE
Union can now take a variable amount of polygons as arguments, instead of only 2.

### PR DESCRIPTION
**Pull request by aurelien-defossez**
It's now possible to do:
`turf.union(poly1, poly2, poly3, poly4);`

### CODE REVIEW

**Comment by tmcw** [comment]
👍 awesome, can you add a testcase to confirm this functionality?

**Comment by aurelien-defossez** [comment]
Done, I added a test with 3 polygons merged into a single one.

**Comment by tmcw** [comment]
👍 awesome, thanks!

**Comment by tmcw** [comment]
Published in turf@3.2.0

**Pull request merged**
