### PR TITLE
Fix typings exports definitions

### PR DESCRIPTION
**Pull request by mfedderly**
In #2400 we added index.d.ts entries to the exports section of the various package.json.
I think that for the typescript packages, the listed file location was incorrect.

This separates handling of the index.d.ts locations into the type of package (js or ts) and then reapplies MRL to update everything.

### CODE REVIEW

**Review by Jungzl — APPROVED** [review]
LGTM

**Review by JamesLMilner — APPROVED** [review]

**Comment by abouroubi** [comment]
Is there any news on when this will be published ?

**Comment by black7375** [comment]
I also have a problem solved by this PR.
I hope there is a release.

**Comment by kevinschaich** [comment]
@abouroubi @black7375 `npm i @turf/turf@7.0.0-alpha.2` did the trick for me

**Pull request merged**
