### PR TITLE
Added intersects from jsts

### PR DESCRIPTION
**Pull request by bozdoz**

### CODE REVIEW

**Comment by DenisCarriere** [comment]
What's the purpose of this module `intersects`?

You can achieve the same `@return {boolean} true/false` by simply using `@turf/intersect` with `!!`.

```javascript
intersect = require('@turf/intersect')
console.log(!!intersect(poly1, poly2))
//=true/false
```

**Comment by bozdoz** [comment]
The purpose is to avoid any costly aggregate function if possible.  Also, please note that this function exists in the jsts library.  I don't think it's outrageous to include it here.

**Comment by DenisCarriere** [comment]
If you could open an [turf issue](https://github.com/Turfjs/turf/issues) and describe in detail what features you want implemented, that way we can have an open discussion on how to implement this.

Another similar issue was opened https://github.com/Turfjs/turf/issues/286 (turf.overlaps).

**Comment by bozdoz** [comment]
Doesn't look like much of a discussion. Good luck!

**Comment by DenisCarriere** [comment]
Unfortunately not... but it's better to open an Issue first, talk about it, then implement it.

**Pull request closed without merging**
