### PR TITLE
New module @turf/great-circle

### PR DESCRIPTION
**Pull request by DenisCarriere**
# New Module! @turf/great-circle 🎉 

Calculate great circles routes as LineString.

**Contributors**

- @springmeyer (using [arc.js](https://github.com/springmeyer/arc.js) as dependency)
- @stepankuzmin (inspired by [`turf-arc`](https://github.com/stepankuzmin/turf-arc))
- @DenisCarriere

image

**JSDocs**

```javascript
/**
 * Calculate great circles routes as {@LineString}
 *
 * @name greatCircle
 * @param {Feature<Point>} start source point feature
 * @param {Feature<Point>} end destination point feature
 * @param {*} [properties={}] line feature properties
 * @param {number} [npoints=100] number of points
 * @param {number} [offset=10] offset controls the likelyhood that lines will
 * be split which cross the dateline. The higher the number the more likely.
 * @returns {Feature<LineString>} arc line feature
 * @example
 * var start = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "Point",
 *     "coordinates": [-122, 48]
 *   }
 * }
 * var end = {
 *   "type": "Feature",
 *   "properties": {},
 *   "geometry": {
 *     "type": "Point",
 *     "coordinates": [-77, 39]
 *   }
 * }
 * var line = turf.greatCircle(start, end, {'name': 'Seattle to DC'});
 * //=line
 */
```

**Benchmark**

```
arc x 21,271 ops/sec ±5.14% (82 runs sampled)
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occured.
- [x] Run `npm run lint` to ensure code style at the turf module level.

CC: @Turfjs/ownership #597

### CODE REVIEW

**Comment by morganherlocker** [comment]
This is maybe a bit on the mushy philosophical side... but is this actually calculating a great circle as it describes?

https://en.wikipedia.org/wiki/Great_circle

I'm +1 on this module, but want to make sure we have precise description of what it's really doing, and that this is useful beyond being a rendering/projection hack.

**Comment by DenisCarriere** [comment]
@morganherlocker good point, should we name the module `@turf/great-circle` instead? That would define the module a bit more from only the name.

I'm 👍 changing it to `great-circle`.

**Comment by morganherlocker** [comment]
I think my question still is: Does this module (or arc.js) actually "`Calculate great circles routes as {@LineString}`"? Does a great circle actually make sense with our coordinate system outside of rendering usecases? Typically we have rejected modules that are purely projection or rendering related with no geospatial analysis value. I'm not saying we should reject this module, but I would like us to think through how this module relates to the scope of turf, which has always been laser focused on geo stats and analysis.

**Comment by DenisCarriere** [comment]
I can't speak too much on the analysis part, however browsing quickly over the source code it references GDAL many times and I'm sure that @springmeyer made sure the calculations were correct.

I also agree that we shouldn't be including projection related modules, however this seems to be a unique case. You might of already seen Google Maps use this type of line representation in their measure tool.

image

Which looks exactly like the one that was created with `@turf/great-circle`.

This module gives the tools needed to create this "look in feel" distance calculator using GeoJSON and easily place that line inside Leaflet or MapboxGL.

**Comment by DenisCarriere** [comment]
Also since the operations are really fast 20K ops/sec, someone would be able to draw a great circle line dynamically without having to let go the mouse which would result in a REALLY slick geo tool.

**Comment by mourner** [comment]
I don't think this is projection-related. It's literally calculating the shortest path between two points on Earth.

**Comment by DenisCarriere** [comment]
Will be published under TurfJS `3.13`

**Pull request merged**
