### PR TITLE
@turf/clone Add return type to function

### PR DESCRIPTION
**Pull request by tunnelpuzzle**
Add return type to clone function instead of `any`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

### CODE REVIEW

**Comment by JamesLMilner** [comment]
Seems sensible to me but @twelch is probably the person to approve this!

**Review by twelch — APPROVED** [review]
Looks good.  Thank you for the contribution!

**Comment by twelch** [comment]
The PR check failure on `yarn install --frozen-lockfile` looks like this improvement has uncovered a type mismatch in turf-nearest-point.  This is a good thing, but a little further work needed to land this.

**Comment by twelch** [comment]
Here's a fix for `packages/turf-nearest-point/index.ts` replacing lines 39-60.  Would you mind adding to your PR @tunnelpuzzle?  Then if tests pass I'll merge.

```
function nearestPoint(
  targetPoint: Coord,
  points: FeatureCollection<Point>
): NearestPoint {
  // Input validation
  if (!targetPoint) throw new Error("targetPoint is required");
  if (!points) throw new Error("points is required");

  let minDist = Infinity;
  let bestFeatureIndex = 0;
  featureEach(points, (pt, featureIndex) => {
    const distanceToPoint = distance(targetPoint, pt);
    if (distanceToPoint < minDist) {
      bestFeatureIndex = featureIndex;
      minDist = distanceToPoint;
    }
  });
  const nearestPoint = points.features[bestFeatureIndex];

  return {
    ...clone(points.features[bestFeatureIndex]),
    properties: {
      ...nearestPoint.properties,
      featureIndex: bestFeatureIndex,
      distanceToPoint: minDist,
    },
  };
}
```

**Comment by tunnelpuzzle** [comment]
Thanks I missed that! I pushed that change for turf-nearest-point. I made a small modification to your code @twelch because I think `nearestPoint.properties` needs to be deep copied in case it has nested properties?

**Comment by twelch** [comment]
Agreed on needing to clone first, good catch.  And thanks again, contributions welcome anytime!

**Pull request merged**
