### PR TITLE
initial commit of polygon split

### PR DESCRIPTION
**Pull request by rowanwins**
This is an inital commit of a polygon split module based on the polyk library
The main drawbacks are that it introduces polyk as a dependency (~5kb minified) and the line has to be a straight line. But it's better than nothing.

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@rowanwins Great stuff!

I'll have a look at it more tomorrow.

First off, it looks like the pre-install tests are failing, looks like there's an issue in the `package.json`.

Looks like there's an issue with `directory`.

```json
 "directories": {
    "test": "test"
  },
```
```
NpmUtilities.installInDir     ("./packages/turf-split", ["benchmark@^1.0.0","tape@^3.5.0","lodash.chunk@^4.2.0","polyk@^0.22.2"])
npm ERR! cb() never called!
@turf/simplify Errored while running BootstrapCommand.execute
npm ERR! cb() never called!
Waiting for 3 child processes to exit. CTRL-C to exit immediately.
```

**Comment by rowanwins** [comment]
Hi @DenisCarriere 

There appears to be error with the polyk package on npm so I've logged a issue with them so stay tuned, once that is fixed all should be resolved. 

That `directories` tag in the package.json can also be deleted I think, I just cut and paste the package.json from somewhere else so it's just a hangover I think

Cheers
R

**Comment by DenisCarriere** [comment]
@rowanwins Doesn't look like PolyK will work long term:

Fallbacks:
- Linestring is limited to two segments
- Dropped decimal precision points
- Output & Input is a very strange array [x1 y1, x2, y2, ...]

However, maybe we can look into the code and reshape it to make it work in a more GeoJSON friendly way, right now it's a giant hack to make it work, it doesn't look clean at all.

**Comment by DenisCarriere** [comment]
I've added tests for PolyK (I had to peak inside your `index.js` "hack" to figure out how to make it work).

https://github.com/MartyWallace/PolyK/pull/10

**Comment by rowanwins** [comment]
Gday @DenisCarriere 

Yeah it was a bit of a limited workaround, I suspect there is probably a fair bit of effort to build it ourselves but maybe we can get there, the thing that concerns me the most is supporting a line with more than 2 vertices and how much tweaking we'd need to do to the algorithm

**Comment by DenisCarriere** [comment]
I still think including `PolyK` is a good idea for now, however in the future we can look into another option or even try to refactor the `Slice` component. It sounds painful to do at first, so lets start off by including it as a dependency and then look into those other options later.

My latest commits should of resolved that npm install issue, they just need to publish a new release now.

**Comment by DenisCarriere** [comment]
Started a new branch `slice` https://github.com/Turfjs/turf/tree/slice

I've included some of your code and fixed the package issue in `PolyK`.

**Pull request closed without merging**
