### PR TITLE
Add turf IDW package - issue #329

### PR DESCRIPTION
**Pull request by miccferr**
Adding a simple IDW surface interpolator in response to issue #329

### CODE REVIEW

**Comment by tmcw** [comment]
@morganherlocker this looks good to me. What do you think about including it in Turf?

**Comment by morganherlocker** [comment]
@miccferr @tmcw This looks good, however, it would be helpful to have a couple things in docs/jsdocs:

1. What does IDW stand for
2. What does IDW do?
3. What sort of generic usecases is this package useful for?

**Comment by miccferr** [comment]
@tmcw @morganherlocker I've added some additional info as requested.

**Comment by morganherlocker** [comment]
Awesome @miccferr, thanks for taking the time to write these docs up! Everything looks great to me.

**Pull request merged**
