### PR TITLE
[@turf/helpers] Fix: First and last position check is not according to the spec

### PR DESCRIPTION
**Pull request by daniel-hauser**
Fixes: #1820

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

### CODE REVIEW

**Comment by daniel-hauser** [comment]
@DenisCarriere Tests are failing also for the `master` branch, the tests of `@turf/helpers` are passing locally

**Comment by DenisCarriere** [comment]
@daniel-hauser seems like the error is coming from another package that this impacts
 bbox-polygon
https://travis-ci.org/Turfjs/turf/builds/640612263#L495

**Comment by daniel-hauser** [comment]
@DenisCarriere 
Looks like in [this](https://github.com/daniel-hauser/turf/commit/e6a0f81b3fbc5dc698e39dc6dd12165c453d85de) commit the call to `validateBBox(bbox)` was removed form `bboxPolygon` and this can explain why the `bboxPolygon` tests are failing

**Comment by mfedderly** [comment]
Closing in favor of https://github.com/Turfjs/turf/pull/2173

**Pull request closed without merging**
