### PR TITLE
Add NodeJS 4, 6, Node to TravisCI testing (Work in progress ⚠️ 80% complete)

### PR DESCRIPTION
**Pull request by DenisCarriere**
## Include CI testing for all NodeJS versions

Refactoring the `test.js` files to support NodeJS 4 will allow us to know if TurfJS compatible with all NodeJS versions without the need of any compilers.

**Note:** UMD (Browser compatible) bundles will only be compiled for `@turf/turf`, all submodules will be NodeJS 4+ compatible and provide CommonJS (`dist/index.js`) + ES Modules (`index.js`).

## TravisCI Tests

- [ ] 4 (Legacy)
- [x] 6 (LTS)
- [x] Node (Latest version)

## Task 1: Convert to pure NodeJS 4 compatible code

- [ ] **Remove any deconstructing**

**Before**

```js
const {foo, bar} = geojson.properties || {};
```

**After**
```js
const properties = geojson.properties || {};
const foo = properties.foo;
const bar = properties.bar;
```

- [ ] **Remove default params**

**Before**

```js
function foo(hello = 'world') {
  return hello;
};
```

**After**
```js
function foo(hello) {
  hello = hello || 'world';
  return hello;
};
```

## ✅ Task 2: Convert Tests to ES6 Modules

- [x] Renamed `index.js` => `index.mjs`
- [x] Renamed `test.js` => `test.mjs`
- [x] Included Rollup config for `test.mjs` => `test.js`

**rollup.config.js**

```js
export default [{
    input: 'index.mjs',
    output: {
        extend: true,
        file: 'index.js',
        format: 'cjs'
    }
}, {
    input: 'test.mjs',
    output: {
        extend: true,
        file: 'test.js',
        format: 'cjs'
    }
}];
```

### CODE REVIEW

**Comment by DenisCarriere** [comment]
🎉 Finally a pass! Going to merge this since it's going to be pretty hard to continue working without these major changes merged.

**Comment by stebogit** [comment]
@DenisCarriere I can't really follow what's going on with this refactoring to adopt ES6, it's all new stuff to me (is it basically just [Rollup](https://rollupjs.org/) that you included?). Sorry I can't really be of help here. 😕 

So meanwhile, to contribute, I thought to work on the `option` parameter thing (https://github.com/Turfjs/turf/issues/944) and the other items in the [list](https://github.com/Turfjs/turf/labels/major-release), but now with the change of `.js` to `.mjs` 😳  I don't even know what to do to develop...  😞 😭 

May I have some hint please? 😅 
I can't wait to learn about this stuff and join you cool kids 🤓 👍

**Comment by rowanwins** [comment]
Gday @stebogit 

Yeah it's a bit daunting at first but checking out rollup is fairly straight forward, by itself it is pretty simple and just converts es6 modules to other formats to make them usable in other js systems like node or the browser. Install it and have a quick play and you'll get it in no time.

You should now be using the mjs files, rollup will generate the index.js file for you , you can see this defined in the master rollup.config.js file in the turf root.

That's not much to go on sorry but once it's tidied up a bit more it should start to make more sense :)

Having said that I think there are still a few broken bits in the workflow of the master branch so perhaps give it another day or so to get things a bit stabilised.

**Comment by DenisCarriere** [comment]
> but now with the change of .js to .mjs 😳 I don't even know what to do to develop... 😞 😭

Maybe this file renaming switch was a bit too much... Instead I'll keep the `index.js` (ES6 modules) and define the Rollup ES5 file to `index.es5.js` (might make more sense).

I tried using `.cjs` extension but `tap` didn't recognize it as a valid file extension 🤔 .

I've created [scripts/update-to-es6-modules.js](https://github.com/Turfjs/turf/blob/master/scripts/update-to-es6-modules.js) to help me refactor the entire library without too much efforts, so major refactoring is a tad easier to do.

**Comment by DenisCarriere** [comment]
@stebogit Refactored the filename extensions (this should make a bit more sense now... 🤞 ) https://github.com/Turfjs/turf/pull/964

> @rowanwins Yeah it's a bit daunting at first

Agreed... the intent with this refactoring isn't to bring any confusion, it should feel like "nothing has changed..." (`.mjs` files are scary 😨)

**Comment by DenisCarriere** [comment]
> I don't even know what to do to develop... 😞 😭

lol... my bad! I'll merge/rebase the `options` task/issue and we can start from a "fresh" install.

**Pull request merged**
