### PR TITLE
Locally failing tests

### PR DESCRIPTION
**Pull request by ath0mas**
Locally running tests results in failures in 3 modules:
- buffer MultiLineString test
- hex-grid grid2 and trigrid2 tests
- midpoint first test precision

(latest commit (3.5.3), win10x64, node 7.0.0, npm 3.10.8, reset node_modules and fresh install+test)

### CODE REVIEW

**Comment by tmcw** [comment]
These pass locally, so the difference may be between node v4 and v7, or between different CPUs.

**Comment by ath0mas** [comment]
Do tests pass on this PR branch for you too?

**Comment by DenisCarriere** [comment]
@ath0mas Just tested your PR branch and it failed using Node v6.

```
# buffer
ok 1 should be equivalent
ok 2 should be equivalent
ok 3 should be equivalent
not ok 4 should be equivalent
  ---
    operator: deepEqual
    expected:
      { features: [ { geometry: { coordinates: [ [ ... ], [ ... ] ], type: 'MultiPolygon' }, properties: { fill: '#000', 'fill-opacity': 0.3, stroke: '#0ff' }, type: 'Feature' }, { geometry: { coordinates: [ [ ..., ..., ..., ... ], [ ..., ..., ... ] ], type: 'MultiLineString' }, properties: {}, type: 'Feature' } ], type: 'FeatureCollection' }
    actual:
      { features: [ { geometry: { coordinates: [ [ ... ], [ ... ] ], type: 'MultiPolygon' }, properties: { fill: '#000', 'fill-opacity': 0.3, stroke: '#0ff' }, type: 'Feature' }, { geometry: { coordinates: [ [ ..., ..., ..., ... ], [ ..., ..., ... ] ], type: 'MultiLineString' }, properties: {}, type: 'Feature' } ], type: 'FeatureCollection' }
    at: Test.<anonymous> (/Users/mac/Github/turf-failing-tests/packages/turf-buffer/test/test.js:13:12)
  ...
ok 5 should be equivalent
ok 6 should be equivalent
ok 7 should be equivalent
ok 8 should be equivalent
```
It's strange that your PR passed with CircleCI which is using node V5.

**Comment by DenisCarriere** [comment]
@ath0mas Sorry for the late merge, I've tested it against Node v7.X and your branch is working on my local environment & CircleCI.

FYI: The latest TurfJS master branch is failing when I'm running the tests Node v7.X (MacOSX).

**Pull request merged**
