### PR TITLE
turf-intersect: new test data with small intersection

### PR DESCRIPTION
**Pull request by zbyte64**
Had an error in my app: 'Uncaught TopologyException: found non-noded intersection between LINESTRING and LINESTRING', issue #463 recommended creating a test case with the failure and that is what this pull request does. On this branch the intersect tests fail with REGEN=true . The added geojson file defines an intersect geometry only 60 inches wide. https://github.com/Turfjs/turf/issues/297#issuecomment-327484653 indicates that JSTS has issues with resolution and may be the cause.

### CODE REVIEW

**Comment by zbyte64** [comment]
Attempted to normalize the precision as described: https://github.com/Turfjs/turf/issues/357 ; issue still persists. Maybe the larger geometry has too many points spanning the small box?

**Comment by DenisCarriere** [comment]
Looks like there's two polygon outers in the Polygon Feature. The inner ring is outside the outer ring.

image

Moved vertices of the "inner" ring.

image

**Comment by zbyte64** [comment]
Is there a function for checking this, like kinks?

**Comment by DenisCarriere** [comment]
There's unlink polygon that might be useful. https://github.com/Turfjs/turf/blob/master/packages/turf-unkink-polygon/README.md

**Comment by zbyte64** [comment]
`kink` doesn't report any kinks. The geometry of the lot is represented as one array in the geojson; how were you able to construct/detect the inner ring?

**Comment by DenisCarriere** [comment]
Oh wait... the Inner & Outer was two polygon shapes in a FeatureCollection 🤦‍♂️  my bad.

It does seem to be a valid GeoJSON according to https://www.mapbox.com/geojsonhint

🤔 ... looking into this.

**Comment by stebogit** [comment]
sorry guys, that typo was driving me crazy 🤣

**Comment by DenisCarriere** [comment]
@stebogit hilarious!

**Comment by DenisCarriere** [comment]
@zbyte64 Made a quick patch fix for this issue, seems like the small inner polygon was throwing a topology error in JSTS, when truncating the precision to 4 and removing any duplicate nodes using `clean-coords` the smaller polygon only had 2 remaining nodes and a valid Polygon needs a minimum of 4 coordinates.

Not an ideal result, but at least it stopped crashing... 👍 

🤔 I couldn't send commits to your PR, so I opened a new one here: https://github.com/Turfjs/turf/pull/1011

**Comment by ilijaz** [comment]
Terrible. Its break all my code, cause i'm try to use turf in precision farming.
Some micro polygons will to be a points. I'm very excited about  #88

**Pull request merged**
