### PR TITLE
New module: Nearest neighbor analysis

### PR DESCRIPTION
**Pull request by muziejus**
Adding a nearest neighbor analysis module. Here are the results of the tests... note that the more negative the z-score, the more clustered. The more positive, the more evenly distributed. If it falls between [-2, 2] or so, then the points are randomly distributed.

**Random points**
screen shot 2017-11-28 at 01 46 55

**Random points with an outlier**
screen shot 2017-11-28 at 01 47 22

**Evenly distributed points (centroids of squaregrid) w/ centroids for reference**
screen shot 2017-11-28 at 01 46 29

**Distribution of centroids of Brazilian states with the bounding box of Brazil as study area w/ centroids for reference**
screen shot 2017-11-28 at 01 45 35

**Distribution of centroids of Brazilian states with Brazil itself as study area w/ centroids for reference**
screen shot 2017-11-28 at 01 45 49

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

Submitting a new TurfJS Module.

- [x] Overview description of proposed module.
- [x] Include JSDocs with a basic example.
- [x] Execute `./scripts/generate-readmes` to create `README.md`.
- [x] Add yourself to **contributors** in `package.json` using "Full Name <@GitHub Username>".

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@muziejus You're on fire! 🔥 

I'll try to find some time to review this.

Also we will wait before merging this so I can publish the next minor release `v5.1`.

**Comment by muziejus** [comment]
Thanks, @DenisCarriere . This is it for a bit, though 🤣 . I don't understand why the Travis tests are failing; it looks related to `turf` itself.

**Comment by DenisCarriere** [comment]
Oh the Travis CI tests were failing because I added a test to make sure all devDependencies are using `*`, however I've recently removed that test because it was impractical. 

```
not ok 3 turf-nearest-neighbor-analysis @turf/truncate devDependencies must use *

  ---

    operator: fail

    at: Test._424‍.r.t (/home/travis/build/Turfjs/turf/packages/turf/test.js:59:56)

    stack: |-

      Error: turf-nearest-neighbor-analysis @turf/truncate devDependencies must use *

          at Test.assert [as _assert] (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/test.js:212:54)

          at Test.bound [as _assert] (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/test.js:64:32)

          at Test.fail (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/test.js:277:10)

          at Test.bound [as fail] (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/test.js:64:32)

          at Test._424‍.r.t (/home/travis/build/Turfjs/turf/packages/turf/test.js:59:56)

          at Test.bound [as _cb] (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/test.js:64:32)

          at Test.run (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/test.js:83:10)

          at Test.bound [as run] (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/test.js:64:32)

          at Immediate.next [as _onImmediate] (/home/travis/build/Turfjs/turf/packages/turf/node_modules/tape/lib/results.js:71:15)

          at runCallback (timers.js:800:20)

  ...

# turf -- strict version dependencies
```

I've updated the branch and it "should" be fixed.

**Comment by DenisCarriere** [comment]
@muziejus Tests are passing ✅ 👍 

I'll merge this and we can always re-open new PRs with minor fixes/tweaks

**Pull request merged**
