### PR TITLE
Point on line fix

### PR DESCRIPTION
**Pull request by rowanwins**
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Have read [How To Contribute](https://github.com/Turfjs/turf/blob/master/CONTRIBUTING.md#how-to-contribute).
- [x] Run `npm test` at the sub modules where changes have occurred.
- [x] Run `npm run lint` to ensure code style at the turf module level.

Gday @DenisCarriere 

Fix for issue #344 by replacing the custom `lineIntersects` function with the new Turf module.

### Benchmark results
````
turf-point-on-line#simple x 302,308 ops/sec ±0.83% (98 runs sampled)
turf-point-on-line#route1 x 153 ops/sec ±0.43% (87 runs sampled)
turf-point-on-line#route2 x 178 ops/sec ±0.35% (85 runs sampled)
````
Seems a little slow for those route scenarios given how fast the simple scenario is so there is probably some optimisation that could take place I suspect.

Even ran the lint and tests check for once ;)

### CODE REVIEW

**Comment by rowanwins** [comment]
Oh and it looks like the CI tests are failing because of a node precision thing in the tests. To get them to pass locally I had the change the values, however running in CI they seem to fail, grrr!

**Comment by DenisCarriere** [comment]
Odd stuff, I'll look into dropping those decimals.

**Comment by DenisCarriere** [comment]
@rowanwins I've been wanted to do this https://github.com/Turfjs/turf/pull/689/commits/b02d6adbaea5eaf23354738554ba9bbbe17a2a7f for a long time, `@turf/point-on-line` always had to manually edit the `expectedLocation` values because of decimals precision (not the module's fault).

**Comment by DenisCarriere** [comment]
@rowanwins Doesn't look like there was any performance loss from adding the `@turf/line-intersect` module.

## Benchmark Results

```
==after (@turf/line-intersect)==
line1 x 234,231 ops/sec ±1.78% (88 runs sampled)
route1 x 161 ops/sec ±1.53% (80 runs sampled)
route2 x 184 ops/sec ±1.96% (80 runs sampled)

==before (original)==
line1 x 272,785 ops/sec ±1.29% (87 runs sampled)
route1 x 195 ops/sec ±2.23% (80 runs sampled)
route2 x 218 ops/sec ±2.42% (78 runs sampled)
```

Those roads are REALLY long! I'm not surprised with these results.

**Pull request merged**
