### PR TITLE
JSTS support ES module

### PR DESCRIPTION
**Pull request by DenisCarriere**
## JSTS support ES module

> ⚠️ Work in progress

First stab at refactoring turf modules which depend on `JSTS` to use ES modules.

So far so good.... Using `jsts@1.4.0`

### JSTS Modules to convert:

- [x] `@turf/buffer`
- [x] `@turf/intersect`
- [x] `@turf/difference`
- [x] `@turf/union`
  - [x] `@turf/mask`

### Other modules to convert to ES Modules:

- [x] `@turf/convex`
- [x] `@turf/polygonize`
- [x] possibly more...

Thanks for the help: @bjornharrtell @skeate

> `rollup-plugin-uglify` is added to see the bundle sizes minified vs. normal bundle

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@bjornharrtell replaced all `jsts` dependant TurfJS modules using the new ES module syntax.

A big relief this is... 👍 This hopefully should shave off ~150-200KB in the overall TurfJS bundle

**Comment by DenisCarriere** [comment]
🎉 🚀 Finally... got ES modules to work with JSTS

**Comment by bjornharrtell** [comment]
Nice! Got any numbers of the (hopefully) size win?

**Comment by DenisCarriere** [comment]
@bjornharrtell Not a bit difference in size, `jsts` will still be a massive bundle in Turf, however it does reduce the `jsts` portion by about 75%. Once the final TurfJS bundle is created using Rollup I'll have a better idea of the final filesize.

**Comment by amenadiel** [comment]
Amazing

**Pull request merged**
