### PR TITLE
Enable typescript strict mode

### PR DESCRIPTION
**Pull request by mfedderly**

### CODE REVIEW

**Comment by JamesLMilner** [comment]
@mfedderly what do you think about turning `strict: true` on in all the `tsconfig.json` files across the repo? That would actually ensure we are always strictly enabled going forward

**Comment by mfedderly** [comment]
All of the individual packages have this tsconfig:

```
{
  "extends": "../../tsconfig.shared.json",
  "compilerOptions": {
    "outDir": "dist/js"
  },
  "files": ["index.ts"]
}
```

By changing tsconfig.shared.json we change them all to enforce strict mode.

**Comment by JamesLMilner** [comment]
> All of the individual packages have this tsconfig:
> 
> ```
> {
>   "extends": "../../tsconfig.shared.json",
>   "compilerOptions": {
>     "outDir": "dist/js"
>   },
>   "files": ["index.ts"]
> }
> ```
> 
> By changing tsconfig.shared.json we change them all to enforce strict mode.

Sorry, yes I missed this! Looks good :)

**Comment by mfedderly** [comment]
@JamesLMilner can you add the github approval so I can merge this later? Thanks!

**Review by JamesLMilner — APPROVED** [review]

**Pull request merged**
