### PR TITLE
Adopt options to all modules (⚠️ Work in progress 15%)

### PR DESCRIPTION
**Pull request by DenisCarriere**
# Adopt `options` object for optional parameters

Ref: https://github.com/Turfjs/turf/issues/944
 
Adding the following syntax to the modules:

## Single optional parameter (Backwards compatible with v4.0)

```js
/**
 * @param {Feature<LineString>} line input line
 * @param {number} distance distance along the line
 * @param {Object} [options] Optional parameters
 * @param {string} [options.units="kilometers"] can be degrees, radians, miles, or kilometers
 */
export default function (line, distance, options) {
    // Backwards compatible with v4.0
    var units = (typeof options === 'object') ? options.units : options;
```

**index.d.ts**

```ts
interface Options {
    units?: Units;
}
export default function along(line: LineString, distance: number, options?: Options): Point;
```

## Multiple optional parameters (❗️ breaking change)

```js
/**
 * @param {Feature<LineString>} line input LineString
 * @param {Object} [options] Optional parameters
 * @param {number} [options.resolution=10000] time in milliseconds between points
 * @param {number} [options.sharpness=0.85] a measure of how curvy the path should be between splines
*/
export default function (line, options) {
    // Optional params
    options = options || {};
    var resolution = options.resolution || 10000;
    var sharpness = options.sharpness || 0.85;

    // validation
    if (typeof options !== 'object') throw new Error('options must be an object');
    if (typeof resolution !== 'number') throw new Error('options must be an number');
    if (typeof sharpness !== 'number') throw new Error('sharpness must be an number');
```

**index.d.ts**

```ts
interface Options {
    resolution?: number;
    sharpness?: number;
}
export default function bezier(line: LineString, options?: Options): LineString;
```

## Apply to the following modules:

- [x] [@turf/along](https://github.com/Turfjs/turf/tree/master/packages/turf-along) (@DenisCarriere)
- [x] [@turf/bearing](https://github.com/Turfjs/turf/tree/master/packages/turf-bearing) (@DenisCarriere)
- [x] [@turf/bezier](https://github.com/Turfjs/turf/tree/master/packages/turf-bezier) (@DenisCarriere)
- [x] [@turf/boolean-point-on-line](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-point-on-line) (@DenisCarriere)
- [x] [@turf/buffer](https://github.com/Turfjs/turf/tree/master/packages/turf-buffer) (@DenisCarriere)
- [x] [@turf/circle](https://github.com/Turfjs/turf/tree/master/packages/turf-circle) (@DenisCarriere)
- [ ] [@turf/clean-coords](https://github.com/Turfjs/turf/tree/master/packages/turf-clean-coords) (@DenisCarriere)
- [ ] [@turf/clusters-dbscan](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters-dbscan) (@DenisCarriere)
- [ ] [@turf/clusters-kmeans](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters-kmeans) (@DenisCarriere)
- [ ] [@turf/concave](https://github.com/Turfjs/turf/tree/master/packages/turf-concave) (@DenisCarriere)
- [ ] [@turf/destination](https://github.com/Turfjs/turf/tree/master/packages/turf-destination) (@DenisCarriere)
- [ ] [@turf/dissolve](https://github.com/Turfjs/turf/tree/master/packages/turf-dissolve) (@DenisCarriere)
- [ ] [@turf/distance](https://github.com/Turfjs/turf/tree/master/packages/turf-distance) (@DenisCarriere)
- [ ] [@turf/flip](https://github.com/Turfjs/turf/tree/master/packages/turf-flip) (@DenisCarriere)
- [ ] [@turf/great-circle](https://github.com/Turfjs/turf/tree/master/packages/turf-great-circle)
- [ ] [@turf/helpers](https://github.com/Turfjs/turf/tree/master/packages/turf-helpers)
- [ ] [@turf/hex-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-hex-grid)
- [ ] [@turf/idw](https://github.com/Turfjs/turf/tree/master/packages/turf-idw)
- [ ] [@turf/inside](https://github.com/Turfjs/turf/tree/master/packages/turf-inside)
- [ ] [@turf/interpolate](https://github.com/Turfjs/turf/tree/master/packages/turf-interpolate)
- [ ] [@turf/isobands](https://github.com/Turfjs/turf/tree/master/packages/turf-isobands)
- [ ] [@turf/isolines](https://github.com/Turfjs/turf/tree/master/packages/turf-isolines)
- [ ] [@turf/line-arc](https://github.com/Turfjs/turf/tree/master/packages/turf-line-arc)
- [ ] [@turf/line-chunk](https://github.com/Turfjs/turf/tree/master/packages/turf-line-chunk)
- [ ] [@turf/line-distance](https://github.com/Turfjs/turf/tree/master/packages/turf-line-distance)
- [ ] [@turf/line-offset](https://github.com/Turfjs/turf/tree/master/packages/turf-line-offset)
- [ ] [@turf/line-overlap](https://github.com/Turfjs/turf/tree/master/packages/turf-line-overlap)
- [ ] [@turf/line-slice-along](https://github.com/Turfjs/turf/tree/master/packages/turf-line-slice-along)
- [ ] [@turf/linestring-to-polygon](https://github.com/Turfjs/turf/tree/master/packages/turf-linestring-to-polygon)
- [ ] [@turf/meta](https://github.com/Turfjs/turf/tree/master/packages/turf-meta)
- [x] [@turf/nearest-point-to-line](https://github.com/Turfjs/turf/tree/master/packages/turf-nearest-point-to-line)
- [ ] [@turf/point-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-point-grid)
- [ ] [@turf/point-on-line](https://github.com/Turfjs/turf/tree/master/packages/turf-point-on-line)
- [ ] [@turf/point-to-line-distance](https://github.com/Turfjs/turf/tree/master/packages/turf-point-to-line-distance)
- [x] [@turf/projection](https://github.com/Turfjs/turf/tree/master/packages/turf-projection)
- [ ] [@turf/random](https://github.com/Turfjs/turf/tree/master/packages/turf-random)
- [ ] [@turf/rewind](https://github.com/Turfjs/turf/tree/master/packages/turf-rewind)
- [ ] [@turf/rhumb-bearing](https://github.com/Turfjs/turf/tree/master/packages/turf-rhumb-bearing) (@stebogit)
- [ ] [@turf/rhumb-destination](https://github.com/Turfjs/turf/tree/master/packages/turf-rhumb-destination) (@stebogit)
- [ ] [@turf/rhumb-distance](https://github.com/Turfjs/turf/tree/master/packages/turf-rhumb-distance) (@stebogit)
- [ ] [@turf/sector](https://github.com/Turfjs/turf/tree/master/packages/turf-sector)
- [ ] [@turf/simplify](https://github.com/Turfjs/turf/tree/master/packages/turf-simplify)
- [ ] [@turf/square-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-square-grid)
- [ ] [@turf/transform-rotate](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-rotate)
- [ ] [@turf/transform-scale](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-scale)
- [ ] [@turf/transform-translate](https://github.com/Turfjs/turf/tree/master/packages/turf-transform-translate)
- [ ] [@turf/triangle-grid](https://github.com/Turfjs/turf/tree/master/packages/turf-triangle-grid)
- [ ] [@turf/truncate](https://github.com/Turfjs/turf/tree/master/packages/turf-truncate)

## Excluded modules (options doesn't apply)

- [x] [@turf/area](https://github.com/Turfjs/turf/tree/master/packages/turf-area)
- [x] [@turf/bbox](https://github.com/Turfjs/turf/tree/master/packages/turf-bbox)
- [x] [@turf/bbox-clip](https://github.com/Turfjs/turf/tree/master/packages/turf-bbox-clip)
- [x] [@turf/bbox-polygon](https://github.com/Turfjs/turf/tree/master/packages/turf-bbox-polygon)
- [x] [@turf/boolean-clockwise](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-clockwise)
- [x] [@turf/boolean-contains](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-contains)
- [x] [@turf/boolean-crosses](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-crosses)
- [x] [@turf/boolean-disjoint](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-disjoint)
- [x] [@turf/boolean-equal](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-equal)
- [x] [@turf/boolean-overlap](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-overlap)
- [x] [@turf/boolean-parallel](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-parallel)
- [x] [@turf/boolean-within](https://github.com/Turfjs/turf/tree/master/packages/turf-boolean-within)
- [x] [@turf/center](https://github.com/Turfjs/turf/tree/master/packages/turf-center)
- [x] [@turf/center-of-mass](https://github.com/Turfjs/turf/tree/master/packages/turf-center-of-mass)
- [x] [@turf/centroid](https://github.com/Turfjs/turf/tree/master/packages/turf-centroid)
- [x] [@turf/clone](https://github.com/Turfjs/turf/tree/master/packages/turf-clone)
- [x] [@turf/clusters](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters)
- [x] [@turf/collect](https://github.com/Turfjs/turf/tree/master/packages/turf-collect)
- [x] [@turf/combine](https://github.com/Turfjs/turf/tree/master/packages/turf-combine)
- [x] [@turf/convex](https://github.com/Turfjs/turf/tree/master/packages/turf-convex)
- [x] [@turf/difference](https://github.com/Turfjs/turf/tree/master/packages/turf-difference)
- [x] [@turf/envelope](https://github.com/Turfjs/turf/tree/master/packages/turf-envelope)
- [x] [@turf/explode](https://github.com/Turfjs/turf/tree/master/packages/turf-explode)
- [x] [@turf/flatten](https://github.com/Turfjs/turf/tree/master/packages/turf-flatten)
- [x] [@turf/intersect](https://github.com/Turfjs/turf/tree/master/packages/turf-intersect)
- [x] [@turf/invariant](https://github.com/Turfjs/turf/tree/master/packages/turf-invariant)
- [x] [@turf/kinks](https://github.com/Turfjs/turf/tree/master/packages/turf-kinks)
- [x] [@turf/line-intersect](https://github.com/Turfjs/turf/tree/master/packages/turf-line-intersect)
- [x] [@turf/line-segment](https://github.com/Turfjs/turf/tree/master/packages/turf-line-segment)
- [x] [@turf/line-slice](https://github.com/Turfjs/turf/tree/master/packages/turf-line-slice)
- [x] [@turf/line-split](https://github.com/Turfjs/turf/tree/master/packages/turf-line-split)
- [x] [@turf/mask](https://github.com/Turfjs/turf/tree/master/packages/turf-mask)
- [x] [@turf/midpoint](https://github.com/Turfjs/turf/tree/master/packages/turf-midpoint)
- [x] [@turf/nearest](https://github.com/Turfjs/turf/tree/master/packages/turf-nearest)
- [x] [@turf/planepoint](https://github.com/Turfjs/turf/tree/master/packages/turf-planepoint)
- [x] [@turf/point-on-surface](https://github.com/Turfjs/turf/tree/master/packages/turf-point-on-surface)
- [x] [@turf/polygon-tangents](https://github.com/Turfjs/turf/tree/master/packages/turf-polygon-tangents)
- [x] [@turf/polygon-to-linestring](https://github.com/Turfjs/turf/tree/master/packages/turf-polygon-to-linestring)
- [x] [@turf/polygonize](https://github.com/Turfjs/turf/tree/master/packages/turf-polygonize)
- [x] [@turf/sample](https://github.com/Turfjs/turf/tree/master/packages/turf-sample)
- [x] [@turf/square](https://github.com/Turfjs/turf/tree/master/packages/turf-square)
- [x] [@turf/tag](https://github.com/Turfjs/turf/tree/master/packages/turf-tag)
- [x] [@turf/tesselate](https://github.com/Turfjs/turf/tree/master/packages/turf-tesselate)
- [x] [@turf/tin](https://github.com/Turfjs/turf/tree/master/packages/turf-tin)
- [x] [@turf/union](https://github.com/Turfjs/turf/tree/master/packages/turf-union)
- [x] [@turf/unkink-polygon](https://github.com/Turfjs/turf/tree/master/packages/turf-unkink-polygon)
- [x] [@turf/within](https://github.com/Turfjs/turf/tree/master/packages/turf-within)

### CODE REVIEW

**Comment by DenisCarriere** [comment]
@stebogit @rowanwins Might need a bit help from you guys on this one :bowtie:

**Comment by stebogit** [comment]
Sure, one at a time we'll fix them all! 👍 
🐢 🐌

**Comment by DenisCarriere** [comment]
🐌 ... haha!

**Comment by DenisCarriere** [comment]
@stebogit This branch should now be good to go. I'm going to track the progress using that checklist in the main comment. Pushing small commits would be best if we are both going to work on it.

**Comment by DenisCarriere** [comment]
## Syntax Guide

## Single optional parameter (Backwards compatible with v4.0)

```js
/**
 * @param {Feature<LineString>} line input line
 * @param {number} distance distance along the line
 * @param {Object} [options] Optional parameters
 * @param {string} [options.units="kilometers"] can be degrees, radians, miles, or kilometers
 */
export default function (line, distance, options) {
    // Backwards compatible with v4.0
    var units = (typeof options === 'object') ? options.units : options;
```

## Multiple optional parameters (❗️ breaking change)

```js
/**
 * @param {Feature<LineString>} line input LineString
 * @param {object} [options] Optional parameters
 * @param {number} [options.resolution=10000] time in milliseconds between points
 * @param {number} [options.sharpness=0.85] a measure of how curvy the path should be between splines
*/
export default function (line, options) {
    // Optional params
    options = options || {};
    var resolution = options.resolution || 10000;
    var sharpness = options.sharpness || 0.85;

    // validation
    if (typeof options !== 'object') throw new Error('options must be an object');
    if (typeof resolution !== 'number') throw new Error('options must be an number');
    if (typeof sharpness !== 'number') throw new Error('sharpness must be an number');
```

**Comment by stebogit** [comment]
> ```js
>export default function (line, distance, options) {
>    // Backwards compatible with v4.0
>    var units = (typeof options === 'object') ? options.units : options;
>```

@DenisCarriere why are we trying to keep backwards compatibility here, if we are clearly/openly moving to a new (breaking) pattern?
Couldn't this be confusing to someone who is switching to the new version, seeing it breaking somewhere but not everywhere?
Or is this just good practice to minimize the number of breaking points?

**Comment by stebogit** [comment]
> Pushing small commits would be best if we are both going to work on it.

👍  @DenisCarriere 
Although if you keep going with this pace ther will be little to do when I'll find some time to work on this in the next few days!! 😄

**Comment by DenisCarriere** [comment]
> Or is this just good practice to minimize the number of breaking points?

👍 It could be very annoying upgrading to v5.0 if all your `units` params will now have to be changed to Objects (`{units: 'kilometers'}`).

For the single Optional parameters we can keep them backwards compatible and any newer modules could use the `options` Object syntax.

For single optional parameters modules, the code is pretty easy to adopt:

## ✅ Backwards compatible with v4.0
```js
export default function (line, distance, options) {
    var units = (typeof options === 'object') ? options.units : options;
```

## ❗️ Breaks v4.0
```js
export default function (line, distance, options) {
    var units = (options || {}).units;
```
Almost no effort to make it backwards compatible (for free).

**Comment by DenisCarriere** [comment]
> Although if you keep going with this pace ther will be little to do when I'll find some time to work on this in the next few days!! 

lol Agreed... I'll slow down eventually (I've got a new coffee machine ☕️ 😄 )

**Comment by DenisCarriere** [comment]
@stebogit I'll claim the modules I'll be updated by adding my name to the end (maybe you could do the same?.. I won't touch those 🙈 ).

- [x] [@turf/along](https://github.com/Turfjs/turf/tree/master/packages/turf-along) (@DenisCarriere)

**Comment by DenisCarriere** [comment]
> @stebogit Couldn't this be confusing to someone who is switching to the new version, seeing it breaking somewhere but not everywhere?

## Typescript (or Flow)

For folks who enjoy strongly enforced Types (using Typescript or Flow), we will enforce the new breaking changes syntax, but for the CommonJS `index.js` files we should be a bit more flexible and not break things too much.

**Comment by stebogit** [comment]
@DenisCarriere quick thought, should we also add a deprecation warning like in the console when the user uses the "old" single parameter definition, so we could safely remove the old stuff in the next major release (or even earlier)?
```js
export default function (line, distance, options) {
    var units = (typeof options === 'object') ? options.units : options;
    if (options && typeof options !== 'object')
        console.warn('Hey dude this is going to break in the next major release!!');
```
(React.js does this, but it hasn't even reached v1.0 yet, so major version updates are quite frequent)

**Comment by DenisCarriere** [comment]
> @stebogit add a deprecation warning

👍 Yep, I've been adding some as I see fit, also don't be scared to add more `throw new Error(message)` that explains the deprecated status.

**Comment by DenisCarriere** [comment]
Merging now before doing significant refactoring to master branch (ref: https://github.com/Turfjs/turf/issues/974)

**Pull request merged**
