### PR TITLE
Adds `@turf/boolean-equal` test

### PR DESCRIPTION
**Pull request by stebogit**
@rowanwins following [this your note](https://github.com/Turfjs/turf/pull/869#issuecomment-319563882) I added the test for `Polygons` with different initial vertices and apparently it works fine 🤔 
Am I doing it properly?

### CODE REVIEW

**Comment by DenisCarriere** [comment]
👍 Looks fine to me, seems like [GeoJSON Equality](https://github.com/geosquare/geojson-equality) handles this correctly.

**Comment by stebogit** [comment]
@DenisCarriere should we add this to the `v.4.6` release?
Not sure what the procedure is to officially release the release 😄

**Comment by DenisCarriere** [comment]
👍 Sure! We can add it to the `v4.6` haven't "officially" published anything, going to publish the TurfJS release when we finish that draft... so anything you want to squeeze in before I publish can go into this release.

**Comment by rowanwins** [comment]
Awesome, glad you didn't have to change a thing :)

**Comment by stebogit** [comment]
Me too 😄

**Pull request merged**
