### PR TITLE
v7.1.0

### PR DESCRIPTION
**Pull request by twelch**
Release 7.1.0 🥳

Publish action is here - https://github.com/Turfjs/turf/actions/runs/10323755696/job/28581809421

### CODE REVIEW

**Review by mfedderly — APPROVED** [review]

**Comment by kachkaev** [comment]
Thanks for releasing @twelch! 

Could you please update releases and CHANGELOG.md? Just got an update PR from Renovate, but it’s uncler what changes are pending.


 - https://github.com/Turfjs/turf/releases
 - https://github.com/Turfjs/turf/blob/master/CHANGELOG.md

Screenshot 2024-08-09 at 21 05 54

**Comment by mfedderly** [comment]
@kachkaev we're giving everyone around the world a chance to work on the release notes but the draft is here https://github.com/Turfjs/turf/releases/tag/untagged-80d231692de18ebbe464

**Comment by kachkaev** [comment]
yeah it shows 404 on my end

**Comment by twelch** [comment]
@kachkaev release notes have been published

**Comment by twelch** [comment]
A new snapshot+update of the docs at turfjs.org will be forthcoming.  We're still dialing that in.

**Pull request merged**
